#+TITLE: Baptism

* When Did The Church Begin?
  
* Spirtit baptism

  1Cor12:13 For by one Spirit are we all baptized into one body, whether we be Jews or Gentiles, whether we be bond or free; and have been all made to drink into one Spirit.

* The one body (Church)

  1Cor12:27 Now ye are the body of Christ, and members in particular.

  1Cor12:28 And God hath set some in the church, first apostles, secondarily prophets, thirdly teachers, after that miracles, then gifts of healings, helps, governments, diversities of tongues.

  Eph1:22 And hath put all things under his feet, and gave him to be the head over all things to the church,

  Eph1:23 Which is his body, the fulness of him that filleth all in all.

  Eph5:30 For we are members of his body, of his flesh, and of his bones.

  Eph5:31 For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh.

  Eph5:32 This is a great mystery: but I speak concerning Christ and the church.

  Col1:18 And he is the head of the body, the church: who is the beginning, the firstborn from the dead; that in all things he might have the preeminence.
