#+TITLE: Bible study
* The Names of the Bible

  Heb4:12 For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart.

  2Tim2:15 Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth.

  Phi2:16 Holding forth the word of life; that I may rejoice in the day of Christ, that I have not run in vain, neither laboured in vain.

  2Cor5:17 Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.

  John6:47 Verily, verily, I say unto you, He that believeth on me hath everlasting life.
  
  Rom1:2 (Which he had promised afore by his prophets in the holy scriptures,)

  Isa66:1 Thus saith the LORD, The heaven is my throne, and the earth is my footstool: where is the house that ye build unto me? and where is the place of my rest?

  Isa66:2 For all those things hath mine hand made, and all those things have been, saith the LORD: but to this man will I look, even to him that is poor and of a contrite spirit, and trembleth at my word.

* The Testimony of Christ   

  John17:17 Sanctify them through thy truth: thy word is truth.

  Titus1:2 In hope of eternal life, which God, that cannot lie, promised before the world began;
